### ISSUE TITLE
Pull request on upstream?

### ISSUE THREAD

**Issue by RedHatter** [orlov-vo/prettier-plugin-svelte#3]
It looks like @UnwrittenFun/prettier-plugin-svelte is active again. Would you create a pull request on upsteam so all your great changes can be merged into the original package?

**Comment by orlov-vo** [comment]
I have different view with author in some points of printing. About it I wrote in [README](https://github.com/orlov-vo/prettier-plugin-svelte#different-from-original). My main goal in printing is make a valid html syntax which you can use in other tools.

We have small discuss about it with author in https://github.com/UnwrittenFun/prettier-plugin-svelte/issues/10

So I will to periodical update this fork from upstream (maybe every week) and publish it to [npm](https://www.npmjs.com/package/@orlov_vo/prettier-plugin-svelte).
